### ISSUE TITLE
yo phovea:update requirements.txt

### ISSUE THREAD

**Issue by anita-steiner** [phovea/generator-phovea#241]
After executing yo phovea:update the generator will add an existing dependency with different version in the requirements.txt
![Screenshot from 2019-11-20 09-17-53](https://user-images.githubusercontent.com/14962506/69221158-e7217f00-0b76-11ea-8858-53fdc203978e.png)

**Comment by thinkh** [comment]
Could you please add the steps to reproduce this error?

**Comment by oltionchampari** [comment]
After testing it for with possible cases i couldn't reproduce the bug.

**Comment by oltionchampari** [comment]
![deps](https://user-images.githubusercontent.com/51322092/72326070-beb58d00-36ae-11ea-923e-10b5ea825ae0.png)
Regarding this issue : 

The init hybrid generator goes through the know libraries and plugins and depending on

 if the  package.json of your current plugin file version contains `-SNAPSHOT`  it takes the 

develop version of the format 
`-e git+https://github.com/phovea/phovea_server.git': '@v2.2.0#egg=phovea_server`

and the master version if not 
`phovea_server: '~=2.0.0'`

It also reads the current version of the dependencies in the requiremenets.txt and the merges 

them together which produces the bug since 
`'-e git+https://github.com/phovea/phovea_server.git': '@v2.2.0#egg=phovea_server`
`'phovea_server: '~=2.0.0`
since the keys are different.

https://github.com/phovea/generator-phovea/blob/451908b99df5a422431b626263b2903ba5696af4/generators/_init-python/index.js#L69-L98
https://github.com/phovea/generator-phovea/blob/451908b99df5a422431b626263b2903ba5696af4/generators/_init-python/index.js#L69-L98
