### ISSUE TITLE
Update to webpack 4

### ISSUE THREAD

**Issue by thinkh** [phovea/generator-phovea#286]
As a first step we want to update to webpack 4 (but still use TypeScript 2.8).

We also need to update the webpack loaders and the syntax of the webpack.config.js.

**Comment by thinkh** [comment]
We should also update the `System.import()` in our TS files as these are deprecated.

We can also remove the following lines from the _tsd.d.ts_ files in web and workspace generator:

https://github.com/phovea/generator-phovea/blob/4c1a48fbaaf5a95f19bcdbb698fa721a791522ba/generators/_init-web/templates/plain/tsd.d.ts#L35-L39

https://github.com/phovea/generator-phovea/blob/4c1a48fbaaf5a95f19bcdbb698fa721a791522ba/generators/workspace/templates/plain/tsd.d.ts#L30-L34

**Comment by dvvanessastoiber** [comment]
### Steps to update to Webpack 4:

#### Prerequesites

- If you have a workspace setup and want to update a single repository, it is necessary to create a __tmp_<repo_name>/_tmp/_ folder and copy paste the concerned repository in this folder.
- In _.yo-rc.json_: If `"type": "app"`, then nginx is required for the build. Copy _nginx-default.conf_ and _Dockerfile_ from phovea_server into the repository. If you have the Docker Extension in VS Code, right-click on the Dockerfile and select `Build Image ...`. Otherwise run `docker build --rm -f "Dockerfile" -t <image_name>:latest "."` Afterwards, search for the right network with `docker network ls` and run `docker run --rm --network=<network_name> -it -p 80:80/tcp <image_name>:latest`. 


#### Tutorial

1. Build locally with Webpack 2 in order to be able to compare the build directory with the one that will be created with Webpack 4 and check for correctness. See Prerequisites
2. Change Scripts and requirements in _package.json_ according to [this commit](https://github.com/Caleydo/ordino/compare/develop...thinkh/webpack4). In _webpack.config.js_, it is necessary to replace `loaders` with `rules` and to remove the `CommonsChunkPlugin` as well as the `UglifyJSPlugin`.
3. Replace the deprecated `System.import()` with `import()`

**Comment by dvvanessastoiber** [comment]
We can remove `json-loader`. Since webpack >= `v2.0.0`, importing of JSON files works by default.

**Comment by dvvanessastoiber** [comment]
The logo has been changed from `svg` t0 `gif`, therefore it is necessary to apply the following changes to _webpack.config.js_:

```
- test: /\.(png|jpg)$/,
+ test: /\.(png|jpg|jpeg|gif)$/,
```

See https://github.com/datavisyn/snpology/pull/457/files
