### ISSUE TITLE
Test polyfill from Sam

### ISSUE THREAD

**Issue by mccalluc** [phovea/generator-phovea#46]
Sam writes:
> can you also try to do https://github.com/phovea/generator-phovea/commit/ea89347f1e59da25aceb54b7e50fc5a643cdfde7 again? It is an alternative approach by injecting a polyfill
>I disabled it again by default

@sgratzl : I think you mean try applying this on other projects and make sure it works? Some concerns:
- The dependency you've introduced on your repo is not pinned.
- Do you want the commented out part uncommented? Is that what should be tested?
- I'm not sure how the behavior should change or be improved. Is there anything to check, beyond making sure it still builds?
- I think it would be safer to test it across all the repos first, and if they all work, then add it to the generator.

**Comment by sgratzl** [comment]
1. I don't think that this is ticket specifically to the generator-template. it is related to multiple projects
2. I tried it a month ago, so there were no pinned versions so far
3. the idea is instead of / in addition to enforing a specific firefox version, we inject the polyfill into the tests as we do it for the applications, e.g. https://github.com/Caleydo/lineup/blob/master/src/index.html#L10. see also https://github.com/phovea/phovea_core/issues/11 e.g. a fetch polyfill is also automatically included.
