### ISSUE TITLE
Option to determine whether to take develop or master branches

### ISSUE THREAD

**Issue by mstreit** [phovea/generator-phovea#80]
At the moment the generator operates on the master branches. We can think about adding a flag that allows users to work on the develop branches.

**Comment by ngehlenborg** [comment]
It might be useful for people who are developing Phovea, but for people who are developing **with** Phovea should be operating using releases from the `master` branch.

**Comment by thinkh** [comment]
Since 2017 it became common to setup a new workspace from an exisiting product (e.g., 
`yo phovea:setup-workspace Caleydo/ordino_product`). The `setup-workspace` command supports the branch flag `-b` (e.g., `yo phovea:setup-workspace -b develop Caleydo/ordino_product`). This works if the product has a develop branch and all dependent repositories in the phovea_product.json are using the develop branch.
